version: '3.8'

networks:
  labnet:
    driver: bridge

volumes:
  rabbitmq_data:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - labnet
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  lester:
    build:
      context: ./lester
    container_name: lester
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - labnet

  trevor:
    build:
      context: ./trevor
    container_name: trevor
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - labnet

  franklin:
    build:
      context: ./franklin
    container_name: franklin
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=localhost
      - RABBITMQ_PORT=5672
    networks:
      - labnet

  michael:
    build:
      context: ./michael
    container_name: michael
    depends_on:
      lester:
        condition: service_started
      trevor:
        condition: service_started
      franklin:
        condition: service_started
    environment:
      - RABBITMQ_HOST=10.35.168.89:5672
      - RABBITMQ_PORT=5672
    networks:
      - labnet